{% set name = "super_state_machine" %}
{% set version = "2.0.2" %}
{% set sha256 = "e038a4c573ab80f157bf726c3036367919704f62cd166eb46837143165035958" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/beregond/super_state_machine
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Super State Machine gives you utilities to build finite state machines
